on:
  push:
  branches: [main]

name: ci

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check formatting
        run: cargo fmt --check

      - name: Run tests
        run: cargo test
